name: portal
version: 1.0.0
description: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  analyzer: 6.4.0
  build_runner: ^2.0.0
  characters: ^1.3.0
  dart_conversion:
    git:
      url: https://github.com/DerWolf01/dart_conversion.git
      ref: main
  logger: ^2.4.0
dev_dependencies:
  http: ^0.13.3
  build_test: ^2.2.0
  lints: ^3.0.0
  test: ^1.25.0